name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm ci

    - name: Build Electron App (Debugging)
      run: npx electron-builder --dir
      env:
        DEBUG: electron-builder

    - name: Build Installer
      run: npm run build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: |
          dist/*.exe
          dist/win-unpacked/
        retention-days: 7
